language: php

sudo: false

php:
  - 7.0
  - 7.1
  - nightly

install:
  - composer install

script:
  - vendor/bin/phpunit

after_success:
  - |
      if [ $TRAVIS_PHP_VERSION == "7.0" ] ; then
        ./vendor/bin/test-reporter --coverage-report=test/coverage/clover.xml
      fi
