language: php
php:
  - 5.6
  - nightly

install:
  - composer install

after_success:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.6" ] ; then CODECLIMATE_REPO_TOKEN=4c0e9b6884bed9b8f2100cac23525603a9064cebcf0ec7444ef510622db18b66 ./vendor/bin/test-reporter --coverage-report=test/coverage/clover.xml ; fi;'
