language: php
php:
  - 7.1
  - nightly

install:
  - composer install

addons:
  code_climate:
    repo_token: 4c0e9b6884bed9b8f2100cac23525603a9064cebcf0ec7444ef510622db18b66

after_success:
  - |
      f [ $TRAVIS_PHP_VERSION == "5.6" ] ; then
        ./vendor/bin/test-reporter --coverage-report=test/coverage/clover.xml
      fi
