SOURCES= \
	src/bind.php \
	src/chain.php \
	src/chunk.php \
	src/compose.php \
	src/concat.php \
	src/filter.php \
	src/indexBy.php \
	src/map.php \
	src/mapcat.php \
	src/max.php \
	src/min.php \
	src/product.php \
	src/reduce.php \
	src/skip.php \
	src/skipN.php \
	src/sum.php \
	src/take.php \
	src/takeN.php \
